version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 18
    commands:
      - npm install

  build:
    commands:
      - npm test

reports:
  cobertura:
    files:
      - coverage/lcov.info
    file-format: LCOV

artifacts:
  files:
    - coverage/lcov.info
    - coverage/coverage-final.json
    - coverage/lcov-report/index.html
build:
  commands:
    - npm test
    - echo "Contenido del archivo lcov.info:"
    - cat coverage/lcov.info || echo "❌ No se generó coverage/lcov.info"
