version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 18
    commands:
      - npm install

    build:
    commands:
      - npm test
      - cat coverage/lcov.info || echo "❌ lcov.info NO ENCONTRADO"

reports:
  cobertura:
    files:
      - coverage/lcov.info
    file-format: LCOV
